import React from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const InsightsExport = ({ 
  selectedLocation, 
  airQualityData, 
  industries, 
  activeHeatmaps, 
  locationInfo,
  correlationData 
}) => {
  
  const generatePDF = async () => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let yPosition = 25;
    
    // Header with branding
    pdf.setFillColor(102, 126, 234);
    pdf.rect(0, 0, pageWidth, 15, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(16);
    pdf.text('🏭 Smokestack - Air Quality Insights Report', 20, 10);
    
    // Location and date
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(14);
    pdf.text(`${locationInfo?.city || 'Unknown Location'}, ${locationInfo?.country || ''}`, 20, yPosition);
    yPosition += 8;
    pdf.setFontSize(10);
    pdf.text(`📍 ${selectedLocation.lat.toFixed(4)}, ${selectedLocation.lon.toFixed(4)} | Generated: ${new Date().toLocaleDateString()}`, 20, yPosition);
    yPosition += 15;
    
    // Capture map screenshot
    try {
      const mapElement = document.querySelector('.leaflet-container');
      if (mapElement) {
        const canvas = await html2canvas(mapElement, {
          useCORS: true,
          allowTaint: true,
          scale: 0.5
        });
        const imgData = canvas.toDataURL('image/png');
        pdf.addImage(imgData, 'PNG', 20, yPosition, 170, 100);
        yPosition += 110;
      }
    } catch (error) {
      console.log('Map screenshot failed, continuing without image');
    }
    
    // Air Quality Summary Box
    pdf.setFillColor(248, 249, 250);
    pdf.rect(20, yPosition, 170, 35, 'F');
    pdf.setDrawColor(102, 126, 234);
    pdf.rect(20, yPosition, 170, 35);
    
    pdf.setFontSize(14);
    pdf.setTextColor(102, 126, 234);
    pdf.text('Air Quality Summary', 25, yPosition + 8);
    
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    const aqiLevel = getAQILevel(airQualityData?.aqi);
    pdf.text(`EU AQI: ${airQualityData?.aqi || 'N/A'} (${aqiLevel})`, 25, yPosition + 18);
    
    if (airQualityData?.components) {
      pdf.setFontSize(10);
      pdf.text(`PM2.5: ${airQualityData.components.pm2_5?.toFixed(1) || 'N/A'} μg/m³`, 25, yPosition + 26);
      pdf.text(`NO2: ${airQualityData.components.no2?.toFixed(1) || 'N/A'} μg/m³`, 80, yPosition + 26);
      pdf.text(`SO2: ${airQualityData.components.so2?.toFixed(1) || 'N/A'} μg/m³`, 130, yPosition + 26);
    }
    yPosition += 45;
    
    // AQI Legend with colors
    pdf.setFontSize(12);
    pdf.setTextColor(102, 126, 234);
    pdf.text('AQI Legend (European Standard)', 20, yPosition);
    yPosition += 10;
    
    const legendItems = [
      { level: '1', color: [0, 228, 0], label: 'Very Good' },
      { level: '2', color: [255, 255, 0], label: 'Good' },
      { level: '3', color: [255, 126, 0], label: 'Fair' },
      { level: '4', color: [255, 0, 0], label: 'Poor' },
      { level: '5', color: [143, 63, 151], label: 'Very Poor' }
    ];
    
    legendItems.forEach((item, index) => {
      const x = 20 + (index * 35);
      pdf.setFillColor(item.color[0], item.color[1], item.color[2]);
      pdf.rect(x, yPosition, 8, 6, 'F');
      pdf.setFontSize(8);
      pdf.setTextColor(0, 0, 0);
      pdf.text(item.level, x + 10, yPosition + 4);
      pdf.text(item.label, x - 5, yPosition + 12);
    });
    yPosition += 25;
    
    // Industries section
    if (industries && industries.length > 0) {
      pdf.setFontSize(12);
      pdf.setTextColor(102, 126, 234);
      pdf.text('Nearby Industries', 20, yPosition);
      yPosition += 8;
      
      pdf.setFontSize(10);
      pdf.setTextColor(0, 0, 0);
      industries.slice(0, 5).forEach((industry, index) => {
        pdf.text(`• ${industry.name} (${industry.type})`, 25, yPosition);
        yPosition += 6;
      });
      yPosition += 5;
    }
    
    // Recommendations
    pdf.setFontSize(12);
    pdf.setTextColor(102, 126, 234);
    pdf.text('Health & Action Recommendations', 20, yPosition);
    yPosition += 8;
    
    const recommendations = getRecommendations(airQualityData?.aqi);
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    recommendations.forEach((rec) => {
      if (yPosition < pageHeight - 20) {
        pdf.text(`• ${rec}`, 25, yPosition);
        yPosition += 6;
      }
    });
    
    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text('Generated by Smokestack Air Quality Monitor | Data sources: OpenWeatherMap, Overpass API', 20, pageHeight - 10);
    
    // Save PDF
    pdf.save(`air-quality-insights-${locationInfo?.city || 'location'}-${new Date().toISOString().split('T')[0]}.pdf`);
  };
  
  const getAQILevel = (aqi) => {
    if (!aqi) return 'Unknown';
    switch(aqi) {
      case 1: return 'Very Good';
      case 2: return 'Good';
      case 3: return 'Fair';
      case 4: return 'Poor';
      case 5: return 'Very Poor';
      default: return 'Unknown';
    }
  };
  
  const getRecommendations = (aqi) => {
    const baseRecs = [
      'Monitor air quality regularly using this tool',
      'Consider location when planning outdoor activities',
      'Support policies for cleaner industrial practices'
    ];
    
    if (!aqi) return baseRecs;
    
    if (aqi >= 4) {
      return [
        'Limit outdoor activities, especially exercise',
        'Consider air purifiers for indoor spaces',
        'Wear N95 masks when outdoors',
        ...baseRecs
      ];
    } else if (aqi >= 3) {
      return [
        'Sensitive individuals should limit outdoor exposure',
        'Avoid heavy outdoor exercise during peak hours',
        ...baseRecs
      ];
    } else {
      return [
        'Air quality is good for outdoor activities',
        'Continue monitoring for changes',
        ...baseRecs
      ];
    }
  };
  
  return (
    <button 
      onClick={generatePDF}
      className="export-btn"
      title="Export insights as PDF with map"
    >
      📄 Export PDF
    </button>
  );
};

export default InsightsExport;